// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvAWrfT3RHpsQzXX6mRtmzLQmQcuou0Nk',
    appId: '1:230543562412:web:9e181bbca1bb07e85a7109',
    messagingSenderId: '230543562412',
    projectId: 'zicta-tariff-comparator',
    authDomain: 'zicta-tariff-comparator.firebaseapp.com',
    storageBucket: 'zicta-tariff-comparator.firebasestorage.app',
    measurementId: 'G-D00011MCCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOe8ou3qe2YJHiFKZ3sCgCJ8BCezhCve4',
    appId: '1:230543562412:android:35a4e42c34e1d39c5a7109',
    messagingSenderId: '230543562412',
    projectId: 'zicta-tariff-comparator',
    storageBucket: 'zicta-tariff-comparator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGLj7fF0k58bJLCXJ9dKz7BUzbRzFuWNs',
    appId: '1:230543562412:ios:ded26b0714bf372a5a7109',
    messagingSenderId: '230543562412',
    projectId: 'zicta-tariff-comparator',
    storageBucket: 'zicta-tariff-comparator.firebasestorage.app',
    androidClientId: '230543562412-4sqm7p6odnpo6r6sdcdp88gmejnr1jeb.apps.googleusercontent.com',
    iosClientId: '230543562412-hmkabnknisqu6dffsq64hj0lfc1c1iad.apps.googleusercontent.com',
    iosBundleId: 'zm.zicta.tarriffcomparator',
  );

}
