name: services_repo
description: Repo for application services
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  local_data:
    git:
      url: https://gitlab+deploy-token-4:4zjU2bJymy7c6vTztanf@gitlab.probasegroup.com/flutter_packages/local_data.git
      ref: 25bcb3354fc6171858c62e33d81410192458969f
  net_source:
    path: ../net_source

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
